version: "3.9"

services:
  ubuntu-web:
    image: awoisoak/photo-shop
    tty: true
  load-balancer:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - ubuntu-web
