- name: All server tasks
  hosts: all
  tasks:
    - name: Update apt
      ansible.builtin.apt:
        update_cache: true

    - name: Install common dependencies
      ansible.builtin.apt:
        pkg:
          - curl
          - dnsutils
          - netcat
          - net-tools
          - iputils-ping



#     - name: Start mysql server
#       ansible.builtin.service:
#         name: mariadb
#         state: started

#     - name: Setup database
#       ansible.builtin.command: mysql -u $MYSQL_USER -p$MYSQL_PASSWORD -h ubuntu-db -P 3306 < /tmp/setup.db.sql
#       register: output
#       changed_when: output # TODO figure out changed_when

# TODO set dynamic inventory
# TODO enable some extra service?

# Use different os family system?


  #TODO we should not run commands with root    
  #TODO use ansible for something else that we already had with docker compose and awoisoak/photo-shop image?    


      # ansible.builtin.command: "{{ item }} chdir=/src/package/"
      # with_items:
      #   - service mysql start
      # register: output