- name: All server tasks
  hosts: all
  tasks:
    - name: Update apt
      ansible.builtin.apt:
        update_cache: true

    - name: Install common dependencies
      ansible.builtin.apt:
        pkg:
          - curl
          - dnsutils
          - netcat
          - net-tools
          - iputils-ping

- name: Check service status
  hosts: localhost
  tasks:
    - name: Check web server and DB connection
      ansible.builtin.uri:
        url: http://localhost:8080
        return_content: true
      register: this
      failed_when: "'Connected to DB' not in this.content"

- name: Setup web servers
  hosts: web_servers
  tasks:
    - name: Create/Ensure group developers exists
      ansible.builtin.group:
        name: developers
        state: present
        gid: 1111

    - name: Create users
      ansible.builtin.user:
        name: winstonsmith
        shell: /bin/bash
        group: developers


# TODO enable some extra service?

# Use different os family system?


  #TODO we should not run commands with root    
  #TODO use ansible for something else that we already had with docker compose and awoisoak/photo-shop image?    


      # ansible.builtin.command: "{{ item }} chdir=/src/package/"
      # with_items:
      #   - service mysql start
      # register: output